version: "3.9"

services:

  kafka-0:
    image: ${IMAGE}
    ports:
      - "9094:9094"
    env_file: .env
    environment:
      # уникальный идентификатор узла
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093

  kafka-1:
    image: ${IMAGE}
    ports:
      - "9095:9094"
    env_file: .env
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://127.0.0.1:9095
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093

  kafka-2:
    image: ${IMAGE}
    ports:
      - "9096:9094"
    env_file: .env
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092,EXTERNAL://127.0.0.1:9096
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    ports:
      - "8080:8080"
    environment:
#     адрес:порт kafka listener-а для подключения UI
#     предполагаю что любого из кластера
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-0:9092,kafka-1:9092,kafka-2:9092
#     думаю что просто внутреннее названия этого кластера
      - KAFKA_CLUSTERS_0_NAME=kraft
#     _0_ это 1 элемент списка. Можно указать несколько кластеров

# на всякий случай еще 1 UI
  ui-kafdrop:
    image: obsidiandynamics/kafdrop:4.1.0
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka-0:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - "kafka-0"
      - "kafka-1"
      - "kafka-2"